spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sahtech
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: nizar123
      roles: USER

app:
  client:
    url: http://localhost:8080/*