spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sahtech
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
## LOGGING ##

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level- %logger{45} - %msg %n"

app:
  client:
    url: http://localhost:8080/*
twilio:
  AccountSID: AC66514c238aaaf64740b3f63cab770271
  AuthToken: 2453a1b2b7c45d2d5523cb2c47191d8c
  phoneNumber: +13346001566
mailersend:
  apiKey: mlsn.d540614a88d96b3bb937b25f85e962c95730ce9b6a199d41f03551fa14ce6363
  fromEmail: nizaraoun1919@gmail.com
  fromName: Nizar Aoun