spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nizaraoun1919@gmail.com
    password: zzxt mvml lftu tlft
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com/sql7712716?useSSL=false
    username: sql7712716
    password: jf5vnKqEeW
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /uploads/**
  resources:
    static-locations: file:E:/PfeProject/BackendSahTech/SahTech/uploads/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

server:
  tomcat:
    max-swallow-size: 20MB

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level- %logger{45} - %msg %n"

app:
  client:
    url: http://localhost:8080/*

twilio:
  AccountSID: AC66514c238aaaf64740b3f63cab770271
  AuthToken: 2453a1b2b7c45d2d5523cb2c47191d8c
  phoneNumber: +13346001566
